FROM openjdk:8-jdk-alpine
ADD target/premptive-sentiment-analyzer-0.0.1-SNAPSHOT.jar premptive-sentiment-analyzer-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["sh","-c","java -jar /premptive-sentiment-analyzer-0.0.1-SNAPSHOT.jar"]
 